/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SimpananIndexRouteImport } from './routes/simpanan/index'
import { Route as PinjamanIndexRouteImport } from './routes/pinjaman/index'
import { Route as LaporanIndexRouteImport } from './routes/laporan/index'
import { Route as AngsuranIndexRouteImport } from './routes/angsuran/index'
import { Route as AnggotaIndexRouteImport } from './routes/anggota/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimpananIndexRoute = SimpananIndexRouteImport.update({
  id: '/simpanan/',
  path: '/simpanan/',
  getParentRoute: () => rootRouteImport,
} as any)
const PinjamanIndexRoute = PinjamanIndexRouteImport.update({
  id: '/pinjaman/',
  path: '/pinjaman/',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanIndexRoute = LaporanIndexRouteImport.update({
  id: '/laporan/',
  path: '/laporan/',
  getParentRoute: () => rootRouteImport,
} as any)
const AngsuranIndexRoute = AngsuranIndexRouteImport.update({
  id: '/angsuran/',
  path: '/angsuran/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnggotaIndexRoute = AnggotaIndexRouteImport.update({
  id: '/anggota/',
  path: '/anggota/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anggota/': typeof AnggotaIndexRoute
  '/angsuran/': typeof AngsuranIndexRoute
  '/laporan/': typeof LaporanIndexRoute
  '/pinjaman/': typeof PinjamanIndexRoute
  '/simpanan/': typeof SimpananIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anggota': typeof AnggotaIndexRoute
  '/angsuran': typeof AngsuranIndexRoute
  '/laporan': typeof LaporanIndexRoute
  '/pinjaman': typeof PinjamanIndexRoute
  '/simpanan': typeof SimpananIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anggota/': typeof AnggotaIndexRoute
  '/angsuran/': typeof AngsuranIndexRoute
  '/laporan/': typeof LaporanIndexRoute
  '/pinjaman/': typeof PinjamanIndexRoute
  '/simpanan/': typeof SimpananIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anggota/'
    | '/angsuran/'
    | '/laporan/'
    | '/pinjaman/'
    | '/simpanan/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/anggota' | '/angsuran' | '/laporan' | '/pinjaman' | '/simpanan'
  id:
    | '__root__'
    | '/'
    | '/anggota/'
    | '/angsuran/'
    | '/laporan/'
    | '/pinjaman/'
    | '/simpanan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnggotaIndexRoute: typeof AnggotaIndexRoute
  AngsuranIndexRoute: typeof AngsuranIndexRoute
  LaporanIndexRoute: typeof LaporanIndexRoute
  PinjamanIndexRoute: typeof PinjamanIndexRoute
  SimpananIndexRoute: typeof SimpananIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simpanan/': {
      id: '/simpanan/'
      path: '/simpanan'
      fullPath: '/simpanan/'
      preLoaderRoute: typeof SimpananIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pinjaman/': {
      id: '/pinjaman/'
      path: '/pinjaman'
      fullPath: '/pinjaman/'
      preLoaderRoute: typeof PinjamanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan/': {
      id: '/laporan/'
      path: '/laporan'
      fullPath: '/laporan/'
      preLoaderRoute: typeof LaporanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/angsuran/': {
      id: '/angsuran/'
      path: '/angsuran'
      fullPath: '/angsuran/'
      preLoaderRoute: typeof AngsuranIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anggota/': {
      id: '/anggota/'
      path: '/anggota'
      fullPath: '/anggota/'
      preLoaderRoute: typeof AnggotaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnggotaIndexRoute: AnggotaIndexRoute,
  AngsuranIndexRoute: AngsuranIndexRoute,
  LaporanIndexRoute: LaporanIndexRoute,
  PinjamanIndexRoute: PinjamanIndexRoute,
  SimpananIndexRoute: SimpananIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
